apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: IGJvb2stcmRzLmM0OXcyZ3V3cXRmMC51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
  db_username: YWRtaW4=
  db_password: c3JpdmFyZGhhbg==
